docs/RULES/README.md

Reading the [available cleanup rules](https://github.com/devopshq/artifactory-cleanup/blob/master/docs/RULES) in [Artifact cleanup policies](https://github.com/devopshq/artifactory-cleanup#artifact-cleanup-policies), using `filter_by_path_mask` gives: 
```
AttributeError: module 'artifactory_cleanup.rules' has no attribute 'filter_without_path_mask'
```
For users which edit config in a non Python environment, having an up2date documentation would be useful (without browsing all Python files files).
=> Updating rules documentation according Python comment content.
**NB**: I haven't tested all rules, I hope no error in multi-parameters rules
----
*PS: So nice cleanup tool 😘*

Fix rules documentation

---

docker/run.sh

There's a small bug in the Dockerfile regarding the check of the ARTIFACTORY_DESTROY_MODE_ENABLED variable.
As an implication of the bug the docker image can not be used to run in destroy mode.

fix check of ARTIFACTORY_DESTROY_MODE_ENABLED in docker image

---

.github/workflows/release.yml
README.md

I've adjusted the Github action manifest in order to use Git tags / releases also as Docker image tags when pushing it to the image repository. Therefore, the `latest` tag will always be set. I presumed, that you might start creating releases on your Github repository. This will now lead the action to get triggered when a tag with the prefix `v*` is getting created. 
For instance, a Git tag `v0.33` will lead to the Docker image tag `0.33` and `latest`. When a PR is created, the action will also get triggered. I prevented pushing to pypa and pushing the Docker image though on a PR. The build step should be done.
I couldn't test this end to end since I haven't access to your registries, so I ask you to test this on your actual repo. I hope you find the additions useful and that all is fine …

Adding Docker image tags from Git tags

---

artifactory_cleanup/rules/filters.py

This PR fixes https://github.com/devopshq/artifactory-cleanup/issues/56. I basically copied what exists for `operator`. Perhaps, `operator` should be renamed to be more descriptive.

Use OR operator for including Docker images

---

docker/Dockerfile

With this change, the container will behave as documented, in particular with respect to self-signed certificates.

Add entrypoint script to container

---

README.md
artifactory_cleanup/rules/keep.py
tests/test_rules_keep.py

This is the fix for devopshq/artifactory-cleanup#80
Also updated the regex to pull out a semantic version, the original wasn't working to pull the version out of the strings. See tests for proof.
Also added a warning message when the version couldn't be identified.

fix:  KeepLatestVersionNFilesInFolder to return the artifact set properly

---

README.md
artifactory_cleanup/rules/base.py
tests/test_custom_rules.py

Custom rules without a doc string crash as `cls.__doc__` is `None`.

Avoid crash on custom rules without doc string

---

artifactory_cleanup/rules/docker.py
tests/test_rules_docker.py

This should fix https://github.com/devopshq/artifactory-cleanup/issues/77.
Before this change, image tags were only grouped by the versioning. This is okay if there is only one image specified but is not correct when multiple images are specified.

Include the path when grouping images for KeepLatestNVersionImagesByProperty

---

artifactory_cleanup/rules/docker.py

This is to allow overriding the value (if importing the artifactory_cleanup package from code) to support non-standard manifest file names, e.g. "list.manifest.json" as emitted from 'docker build --cache-to/--cache-from command'
Change inspired by my colleague who worked out how to clean up image caches in the first place.

refactor manifest.json file into a module constant

---

README.md
artifactory_cleanup/rules/docker.py
tests/test_rules_docker.py

Allows using `KeepLatestNVersionImagesByProperty` with semver tags that are prefixed with a 'v'.
* <https://semver.org/#is-v123-a-semantic-version>
* Resolves #92

Adds support for semver prefixed with 'v' (e.g., 'v1.2.3')

---

README.md
artifactory_cleanup/rules/delete.py

Allows using `DeleteByRegex` for removing artifacts by redex
Resolves  #111

Added a rule for removing artifacts by regex

---

README.md
artifactory_cleanup/cli.py

Fix #124
Here is what I tested.
```shell
$ cat artifactory-cleanup-1.yaml
artifactory-cleanup:
server: https://artifactory.example.com/artifactory
user: $ARTIFACTORY_USERNAME
password: $ARTIFACTORY_PASSWORD
policies:
- name: Remove all files from repo-name-here older than 7 days
rules:
- rule: Repo
name: "test-artifacts-local"
- rule: DeleteOlderThan
days: 65535
$ env | grep ARTIFACTORY_CLEANUP
ARTIFACTORY_CLEANUP_CONFIG_FILE=artifactory-cleanup-1.yaml
ARTIFACTORY_CLEANUP_DESTROY=True
$ artifactory-cleanup
********************************************************************************
Destroy MODE
Checking 'test-artifacts-local' repository exists.
The test-artifacts-local repository exists.
Add AQL Filter - rule: Repo - Apply the policy to one repository.
Before AQL query: []
After AQL …
```

Add environment variables for parameters

---

README.md
artifactory_cleanup/artifactorycleanup.py
artifactory_cleanup/cli.py

also add missing readme for ignore-not-found

add threads flag to use threads

---

artifactory_cleanup/loaders.py

Expand environment variables also for `server` (similar to fields `user` and `password`) .

Support environment variables in server config

---

README.md
artifactory_cleanup/artifactorycleanup.py
artifactory_cleanup/cli.py

Hello,
I am also interested in the feature from [Pull Request #136](https://github.com/devopshq/artifactory-cleanup/pull/136)
I have rebased the feature branch on master, squashed the commits, and made some modifications.
@roytev  introduced a new option, `--output-artifacts`, which only worked with the specific combination of `--output ... --output-format json --output-artifacts`
As an alternative, I added a new `--output-format` named `json-with-artifact-list`, which I find to be more understandable.

feat(output): save list of deleted artifacts as json

---

artifactory_cleanup/cli.py
artifactory_cleanup/loaders.py
tests/data/all-built-in-rules.yaml
tests/test_loaders.py

Implementation of Artifactory API Key.
User and password are still required if the apikey configuration entry is missing.
The apikey is used when provided and is not an empty string.

API Key implementation

---

artifactory_cleanup/rules/delete.py
artifactory_cleanup/rules/docker.py

Fix unwanted artifact deletion with checking remote_downloads field

---

README.md
artifactory_cleanup/rules/delete.py
artifactory_cleanup/rules/utils.py

Implements suggestion from #130

Add LRU cleanup for generic repositories

---

README.md

fixes #159
hmm i am wondering how this worked before... i found it two times.
But seems like this new feature is long needed, because new reports come in. At least one positive thing... Sorry for all the issues.

README: fix regex in strings

---

artifactory_cleanup/rules/docker.py
tests/test_rules_docker.py

Allow more custom version when used with corresponding custom regex
e.g.
- version with prefix (uat-1.2.3)
- any other version structure if there is at least an int for major, minor and patch in this order (see added tests)

Improve rule KeepLatestNVersionImagesByProperty

---

docker/Dockerfile

There are some CVEs currently set in buster that are a bit problematic for some security scans (i.e. CVE-2021-33574). So I would like to propose to bump to the more recent bookworm images that normally should have less security vulnerabilities.
Let me know if you may also want to bump to 3.10, since the GitHub actions is anyway [deploying with 3.10 and not 3.9](https://github.com/devopshq/artifactory-cleanup/blob/master/.github/workflows/release.yml#L22C10-L22C33).
Also, I took the opportunity to fix this legacy syntax:
```
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 6)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 9)
```

Bump to bookworm image for Docker image
